### ISSUE TITLE
Migrate error

### ISSUE THREAD

**Issue by winter-ice** [kenepa/translation-manager#13]
` SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB, TEXT, GEOMETRY or JSON column 'text' can't have a default value`

**Comment by musa11971** [comment]
Hi, what database engine and version are you using?

**Comment by winter-ice** [comment]
> 

innodb
8.0.29

**Comment by winter-ice** [comment]
> in your `config/database.php`, change the value of **engine** in **mysql** connections to **innodb**
> 
> ```
> 'engine' => 'innodb'
> ```

Doesn't work

**Comment by DevRaeph** [comment]
Same

**Comment by mohssineAboutaj** [comment]
i think you need to upgrade, [check here](https://laracasts.com/discuss/channels/servers/1101-blob-text-geometry-or-json-column-dealstatus-cant-have-a-default-value)

**Comment by musa11971** [comment]
Issue not related to the package

**Comment by niccolofavari** [comment]
As per [Laravel Documentation](https://laravel.com/docs/10.x/migrations#default-expressions)

> The default modifier accepts a value or an Illuminate\Database\Query\Expression instance. Using an Expression instance will prevent Laravel from wrapping the value in quotes and allow you to use database specific functions. One situation where this is particularly useful is when you need to assign default values to JSON columns

So the migration should be:

```
        Schema::create('language_lines', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('group')->index();
            $table->string('key')->index();
            $table->json('text')->default(new \Illuminate\Database\Query\Expression('(JSON_ARRAY())'));
            $table->timestamps();
        });
```

Hope this helps :)

**Comment by paulohenriquesg** [comment]
It really does help! 

Maybe a PR to change the README would be nice :)

**Comment by buzkall** [comment]
I've done the PR -> https://github.com/kenepa/translation-manager/pull/20
