### ISSUE TITLE
Translations for spanish and catalan

### ISSUE THREAD

**Issue by pardalsalcap** [kenepa/translation-manager#24]
Hi!

not an issue, I have just discovered your plugin and had added translations to my locales, in case you are interested on using them:
[translation-manager.zip](https://github.com/kenepa/translation-manager/files/13319887/translation-manager.zip)

es: Spanish (from Spain) es_ES
ca: Catalan (from Spain) ca_ES

Thanks for sharing your work!

**Comment by Jehizkia** [comment]
Hi, thank you for providing translations. Could you please provide them in the form of a pull request?

**Comment by pardalsalcap** [comment]
Sure! I'll do it shortly

**Comment by pardalsalcap** [comment]
Just ask for the pull request, hope I did it correctly.
