### ISSUE TITLE
Suggestion for a simpler translation UI

### ISSUE THREAD

**Issue by bilogic** [kenepa/translation-manager#32]
Hi!

Great work here! I have a suggestion though, as an example let us translate from IT to ES

## 3 columns
1. Show `text` in IT on line 1 and a dimmed/darked `group` and `key` on line 2
2. Show a `TextInputColumn` filled with translated ES text if available
3. Green tick if translation exists, otherwise red tick, filterable

So if another translator is proficient in EN and ES, they just have to choose EN for column 1. The `group` and `key` are there to help give context for the developer when translator ask clarifying questions. Red/Green is to help quickly see what needs to be worked on.

Make sense? Thank you!

**Comment by Jehizkia** [comment]
Hey, thank you for your suggestion. Could you maybe provide a simple visual example?

**Comment by bilogic** [comment]
| Reference (IT)   | Translated (ES) | Completed |
| ---------------- | ----------------| --------- | 
| -         <br>*navigation.login*     |  acceso         |✅        |
| **aprire** <br>*navigation.open*          |                 |❌        |

**Comment by bilogic** [comment]
Possible?

**Comment by bilogic** [comment]
Any ideas? Thank you.

**Comment by Jehizkia** [comment]
Yes, my bad for the late reply. But yes It's possible. I'll add it to the road map to implement
