### ISSUE TITLE
Text instead of flag for language switcher

### ISSUE THREAD

**Issue by bilogic** [kenepa/translation-manager#33]
Is there an option use only text for the language switcher?
Flags are not entirely representative and it can also refer to currencies on some websites, leading to confusion.

**Comment by Jehizkia** [comment]
In the `config/translation-manager.php`, you'll need to set the option `'show_flags'` to `false` to disable the flags.

```php

/*
    |--------------------------------------------------------------------------
    | Flags or Initials
    |--------------------------------------------------------------------------
    |
    | Control whether to express locales using international flags, or through locale initial letters if disabled in the language switcher.
    |
    */

    'show_flags' => false,
```

**Comment by bilogic** [comment]
I noticed that text version does not indicate the current language, small issue though. Thanks!

**Comment by cawecoy** [comment]
Also, I need to define custom text for each language, in my case it would be: EN, PL, CZ, etc. Thanks for the awesome work in this plugin!

**Comment by rgut13rrez** [comment]
@Jehizkia sorry for the ping. If the flag option is set to false, how can we display the initial letters instead? When I disable the flags all I see now is a black circle.

**Comment by Jehizkia** [comment]
@rgut13rrez It should not show a black circle; it should show a translation logo like this:
![Screenshot 2024-11-07 at 09 11 57](https://github.com/user-attachments/assets/dab46421-486b-4037-bcc8-c77e3ceeffb0)

Which version of the package and filament are you running ? Could you please provide a screenshot?

About your question: would you like to display the initial letters in place of where the flag is displayed?

**Comment by rgut13rrez** [comment]
@Jehizkia This is what I am seeing:
<img width="328" alt="Screenshot 2024-11-07 at 09 14 45" src="https://github.com/user-attachments/assets/1875f6bc-ef61-4108-aead-9589f27b6234">

I am on 4.0.12

And yes, I would like to display the initial letters where the flag is displayed.

Also, the issue appears to be a background color being set on the div: bg-[#030712]

<img width="844" alt="Screenshot 2024-11-07 at 09 23 39" src="https://github.com/user-attachments/assets/6fc06d08-72be-4cf4-8d54-6390f29d80f9">


Thanks

**Comment by rgut13rrez** [comment]
I think I narrowed it down to one thing. I went ahead and added it to my users panel and it was displaying fine, but then I forgot I had not added the required line ('./vendor/kenepa/translation-manager/resources/**/*.blade.php',) to the tailwind.config.js file, and when I added it and ran the build the black background was added.
