### ISSUE TITLE
Ignore or Allow only specific translation file in sync command?

### ISSUE THREAD

**Issue by lakuapik** [kenepa/translation-manager#35]
Thank you for this great package,

Just wondering, would it be possible for an enhancement to ignore/allow specific translation file when we run sync command?

Let say i dont want to include laravel's default translations file.

Maybe add configuration to specify it which file to include or ignore in sync command?

Feel free to drop / discuss this issue, thanks!

**Comment by lakuapik** [comment]
If you are okay, i will draft a PR.

**Comment by Jehizkia** [comment]
Thank you very much. I'll hold off on this one for now as I don't want to have to many functionalities in the translation manager for now. I
