### ISSUE TITLE
Synchronization for Language Resources Under Vendor Folders

### ISSUE THREAD

**Issue by darpadev** [kenepa/translation-manager#38]
Hi,
Thank you for the amazing package. It's very simple, yet useful.

Currently, I'm importing the Filament's language resources and they are imported under the vendor folder.

However, for the synchronization process, I noticed that the syncing vendor's language resources are still pending. 
I planned to develop the code so that I could sync the language resources under the vendor folders. 

If the path of the vendor's language resource is 
`vendor/filament/en/components/button.php` 

and contains 
`"message" => ["uploading_file" => "Uploading file . . ."]`

What is the correct value for the `group` and `key` to be stored in the `language_lines` table:

Option 1:
`group`: components
`key`: button.message.uploading_file

Option 2:
`group`: filament
`key`: components.button.message.uploading_file

Option 3:
`group`: vendor
`key`: filament.components.button.message.uploading_file

**Comment by Jehizkia** [comment]
Hey, thank you for your questions. For now, I haven't really thought about it yet, but I think for vendors, it would become a combination of option 2 and 3.

`group`: vendor.filament.actions
`key`: edit
