### ISSUE TITLE
Error when english is removed from available locales 

### ISSUE THREAD

**Issue by Rattone** [kenepa/translation-manager#39]
Simply comment english and uncomment "nl" or any others language 

```
'available_locales' => [
//        ['code' => 'en', 'name' => 'English', 'flag' => 'gb'],
        ['code' => 'nl', 'name' => 'Nederlands', 'flag' => 'nl'] ,
],
```

![image](https://github.com/kenepa/translation-manager/assets/7362607/6b37a7ba-e983-4235-a4ea-5b30d77d8e0b)

**Comment by swrtom** [comment]
It happens to me even with english translation. Fresh installation

Edit : fixed while adding another translation (fr for my case). Make sure you have lang/fr.json (or lang/nl.json in your case)

**Comment by Jehizkia** [comment]
Thanks for reporting!
