### ISSUE TITLE
Plugin can sync with php lang files?

### ISSUE THREAD

**Issue by webfather2023** [kenepa/translation-manager#42]
It parses these files perfectly, but what if i want to update my lang files after updating it in admin panel?
I'm not sure there is this functional, or maybe it is not working for filament 3.2.56?

**Comment by Jehizkia** [comment]
If you update your lang files you'll just need to press the "synchronize" button and everything well be reflected again in the admin panel.

**Comment by lguichard** [comment]
@Jehizkia @webfather2023 said that we need a button to sync database to php lang file. After updating translations in admin panel it seems usefull to sync php lang file from database lines. 

Do you have a plan to make this feature ? I can propose a PR ?
