### ISSUE TITLE
How to actually use it .. ?

### ISSUE THREAD

**Issue by Saad5400** [kenepa/translation-manager#45]
I've followed the installation process. But how can I actually start adding translation keys/values and which function to use to get the translation depending on the locale and such.

**Comment by Jehizkia** [comment]
Now that you have everything installed, you should have a `lang` folder in your project with your translation keys. For example:

```php
// lang/welcome.php
return [
    'message' => "Welcome to your dashboard"
];
```

Within the translation-manager interface, you can press the "synchronize" button. This will make all your translations from the `lang` folder appear in the table.

To translate a key, select the item you'd like to translate, and you'll be directed to the translation page. Add your translation for the desired language.

To use the translations in your code, you can use the following approaches:

```php
__('welcome.message')
// or
trans('welcome.message')
```

When a user switches the language using the language switcher, the active session's language will be set, and the appropriate translation will be displayed to the user.

**Comment by Saad5400** [comment]
Thanks, much appreciated
