### ISSUE TITLE
Minor UI issues

### ISSUE THREAD

**Issue by daar** [kenepa/translation-manager#5]
The "quick translate" page shows some minor inconsistencies. The vertical alignment is not uniform for elements, as well one might want to use a card to align all elements.

![image](https://github.com/kenepa/translation-manager/assets/865062/b1c3cc97-3915-468a-940a-8cf18d6b06a9)

**Comment by musa11971** [comment]
Cannot seem to reproduce. Pull requests welcomed if this is an actual problem and can be fixed.
