### ISSUE TITLE
Examples needed

### ISSUE THREAD

**Issue by KONEY** [kenepa/translation-manager#59]
Hello!

is a working example of the implementation available?

I can't get past the gate step due to a "Class "App\Providers\Gate" not found" error. I believe there's something to add to the USE section but no indication is fount within the guide.

Thanks

**Comment by RoseRiyadh** [comment]
I'm  using:
`use Illuminate\Support\Facades\Gate;`
hoping this answers you concern

**Comment by KONEY** [comment]
Thanks, yes! I eventually figured it out myself by some trial and error. Still, an installation example would be quite useful!

**Comment by Jehizkia** [comment]
Thanks for the feedback. I've updated the example.
