### ISSUE TITLE
Syntax error: 7 ERROR: syntax error at or near "group" using postgresql

### ISSUE THREAD

**Issue by tuseto** [kenepa/translation-manager#61]
When search into the search input it throws an exception:
`SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "group" LINE 1: ...) as aggregate from "language_lines" where (lower(group::tex..`

The database is postgresql so because there is no `(JSON_ARRAY())` as in the docs
 I've used just `->default(json_encode([]))`
 
 "name": "kenepa/translation-manager",
"version": "4.0.11",

"name": "laravel/framework",
"version": "v11.26.0",

Shared error: [https://flareapp.io/share/dPbERpAm](url)

**Comment by Jehizkia** [comment]
Hi thanks for reporting,

I'm not familar with this issue. But could you maybe try to use `json_build_array()` which is supported by postgresql according to: https://www.postgresql.org/docs/9.4/functions-json.html.

**Comment by tuseto** [comment]
@Jehizkia same.

I am wondering can the issue be with that group is a keyword in postgresql?
I am not aware of how this query exactly is built because laravel query builder should take care of such problem

**Comment by Jehizkia** [comment]
Ah yes, you are correct. I managed to kind of replicate the issue outside of the project by running a similar query. I'll dive deeper into the issue.
