### ISSUE TITLE
not working using shield

### ISSUE THREAD

**Issue by MKWebDesign** [kenepa/translation-manager#7]
Hi, cannot get it working using shield

**Comment by MKWebDesign** [comment]
Hi there

Sorry for the short description ;o)
I’m using the filament plugin ‘shield’ https://filamentphp.com/plugins/shield
After installing the translation manager I can set the permissions in ‘shield’ but on the left side in the navigation bar there is no translation option.
Setting in the appserviceprovider did not work.
Gate::define('use-translation-manager', function (?User $user) {
    // Your authorization logic
    return $user !== null && $user->hasRole('super_admin');
});

Hope you can help me out!

Regards
     Martin
***@***.***
***@***.***


___________
MKWebDesign
M.V.J. Knops

Postadres:
Rennemigstraat 19D
6413 BR HEERLEN

Bezoekadres:
Ganzeweide 68a
6413 GH Heerlen

gsm  +31 (0)61-505 53 75
http://www.mkwebdesign.nl<http://www.mkwebdesign.nl/>


===========================================================
De informatie verzonden met dit e-mail bericht is uitsluitend bestemd voor de geadresseerde. Gebruik van deze informatie door anderen dan de geadresseerde is verboden. Openbaarmaking, vermenigvuldiging, verspreiding en of verstrekking van deze informatie aan derden is niet toegestaan. Afzender staat niet in voor de juiste en volledige overbrenging van de inhoud van een verzonden e-mail, noch voor de tijdige ontvangst daarvan.
===========================================================


Van: Musa ***@***.***>
Datum: woensdag, 17 mei 2023 om 14:22
Aan: kenepa/translation-manager ***@***.***>
CC: Martin Knops ***@***.***>, Author ***@***.***>
Onderwerp: Re: [kenepa/translation-manager] not working using shield (Issue #7)

Please provide more information about the exact issue you are facing and how to reproduce it.

**Comment by musa11971** [comment]
I'm not entirely sure how shield works, but maybe you could try the following.

```php
Gate::define('use-translation-manager', function (?User $user) {
    return $user !== null && $user->hasPermission('translator');
});
```

And assign the permission `translator` to the user/role.

**Comment by MKWebDesign** [comment]
Hi

Thanks for the reply
To bad, it is not working……

Regards
       Martin

___________
MKWebDesign
M.V.J. Knops

Postadres:
Rennemigstraat 19D
6413 BR HEERLEN

Bezoekadres:
Ganzeweide 68a
6413 GH Heerlen

gsm  +31 (0)61-505 53 75
http://www.mkwebdesign.nl<http://www.mkwebdesign.nl/>


===========================================================
De informatie verzonden met dit e-mail bericht is uitsluitend bestemd voor de geadresseerde. Gebruik van deze informatie door anderen dan de geadresseerde is verboden. Openbaarmaking, vermenigvuldiging, verspreiding en of verstrekking van deze informatie aan derden is niet toegestaan. Afzender staat niet in voor de juiste en volledige overbrenging van de inhoud van een verzonden e-mail, noch voor de tijdige ontvangst daarvan.
===========================================================


Van: Musa ***@***.***>
Datum: donderdag, 18 mei 2023 om 14:43
Aan: kenepa/translation-manager ***@***.***>
CC: Martin Knops ***@***.***>, Author ***@***.***>
Onderwerp: Re: [kenepa/translation-manager] not working using shield (Issue #7)

I'm not entirely sure how shield works, but maybe you could try the following.

Gate::define('use-translation-manager', function (?User $user) {

    return $user !== null && $user->hasPermission('translator');

});

And assign the permission translator to the user/role.

**Comment by bvdhsoftware** [comment]
@MKWebDesign Hi Martin, I am working on a solution for Shield. Do you still need it? Let me know then I can share te solution with you. Kind regards :)

**Comment by MKWebDesign** [comment]
Hi

Cool!!!!! It would be great!!!

Regards
      Martin

___________
MKWebDesign
M.V.J. Knops

Postadres:
Rennemigstraat 19D
6413 BR HEERLEN

Bezoekadres:
Ganzeweide 68a
6413 GH Heerlen

gsm  +31 (0)61-505 53 75
http://www.mkwebdesign.nl<http://www.mkwebdesign.nl/>


===========================================================
De informatie verzonden met dit e-mail bericht is uitsluitend bestemd voor de geadresseerde. Gebruik van deze informatie door anderen dan de geadresseerde is verboden. Openbaarmaking, vermenigvuldiging, verspreiding en of verstrekking van deze informatie aan derden is niet toegestaan. Afzender staat niet in voor de juiste en volledige overbrenging van de inhoud van een verzonden e-mail, noch voor de tijdige ontvangst daarvan.
===========================================================


Van: bvdhsoftware ***@***.***>
Datum: dinsdag, 23 mei 2023 om 11:07
Aan: kenepa/translation-manager ***@***.***>
CC: Martin Knops ***@***.***>, Mention ***@***.***>
Onderwerp: Re: [kenepa/translation-manager] not working using shield (Issue #7)

@MKWebDesign<https://github.com/MKWebDesign> Hi Martin, I am working on a solution for Shield. Do you still need it? Let me know then I can share te solution with you. Kind regards :)
